import type { Place } from "@/types";

/**
 * Hardcoded places in Stuttgart for MVP demo
 */
export const STUTTGART_PLACES: Place[] = [
  // ACCOMMODATION
  {
    id: "hostel-1",
    name: "Jugendherberge Stuttgart International",
    description: "Youth hostel with dorms starting at 25€/night. Great location near the center.",
    category: "accommodation",
    coordinates: { lat: 48.7823, lng: 9.1751 },
    price: 25,
    currency: "EUR",
    rating: 4.2,
    address: "Haußmannstraße 27, 70188 Stuttgart",
    tags: ["hostel", "budget", "backpacker", "cheap", "dorm"],
  },
  {
    id: "hostel-2",
    name: "Alex 30 Hostel",
    description: "Modern hostel with private rooms from 35€. Free WiFi and breakfast included.",
    category: "accommodation",
    coordinates: { lat: 48.7695, lng: 9.1707 },
    price: 35,
    currency: "EUR",
    rating: 4.5,
    address: "Alexanderstraße 30, 70184 Stuttgart",
    tags: ["hostel", "modern", "wifi", "breakfast", "budget"],
  },
  {
    id: "hotel-1",
    name: "Motel One Stuttgart",
    description: "Design budget hotel. Rooms from 79€/night with great city views.",
    category: "accommodation",
    coordinates: { lat: 48.7761, lng: 9.1803 },
    price: 79,
    currency: "EUR",
    rating: 4.3,
    address: "Lautenschlagerstraße 14, 70173 Stuttgart",
    tags: ["hotel", "design", "modern", "city center"],
  },

  // FOOD - KEBAB
  {
    id: "kebab-1",
    name: "Vatan Döner",
    description: "Best döner in Stuttgart according to locals. Huge portions, authentic taste.",
    category: "food",
    coordinates: { lat: 48.7789, lng: 9.1756 },
    price: 6,
    currency: "EUR",
    rating: 4.7,
    address: "Eberhardstraße 35, 70173 Stuttgart",
    tags: ["kebab", "döner", "turkish", "cheap", "fast food", "best"],
  },
  {
    id: "kebab-2",
    name: "Memo's Kebab Haus",
    description: "Family-run kebab shop. Try their special sauce! Open until 3am.",
    category: "food",
    coordinates: { lat: 48.7734, lng: 9.1698 },
    price: 5,
    currency: "EUR",
    rating: 4.4,
    address: "Tübinger Straße 20, 70178 Stuttgart",
    tags: ["kebab", "döner", "late night", "cheap"],
  },
  {
    id: "kebab-3",
    name: "Istanbul Grill",
    description: "Turkish restaurant with amazing kebab platters. Great for groups.",
    category: "food",
    coordinates: { lat: 48.7812, lng: 9.1889 },
    price: 12,
    currency: "EUR",
    rating: 4.3,
    address: "Neckarstraße 155, 70190 Stuttgart",
    tags: ["kebab", "turkish", "restaurant", "grill", "group"],
  },

  // FOOD - OTHER
  {
    id: "restaurant-1",
    name: "Weinstube Fröhlich",
    description: "Traditional Swabian cuisine. Try the Maultaschen! Cozy atmosphere.",
    category: "food",
    coordinates: { lat: 48.7745, lng: 9.1821 },
    price: 18,
    currency: "EUR",
    rating: 4.6,
    address: "Leonhardstraße 5, 70182 Stuttgart",
    tags: ["german", "swabian", "traditional", "wine", "maultaschen"],
  },
  {
    id: "restaurant-2",
    name: "Cafe Königsbau",
    description: "Historic café with excellent cakes and coffee. Perfect for breakfast.",
    category: "food",
    coordinates: { lat: 48.7779, lng: 9.1787 },
    price: 12,
    currency: "EUR",
    rating: 4.4,
    address: "Königstraße 28, 70173 Stuttgart",
    tags: ["cafe", "breakfast", "coffee", "cake", "historic"],
  },

  // EVENTS
  {
    id: "event-1",
    name: "Bitcoin Stammtisch Stuttgart",
    description: "Monthly Bitcoin meetup. Discuss crypto, network with enthusiasts. Every first Thursday.",
    category: "event",
    coordinates: { lat: 48.7767, lng: 9.1732 },
    price: 0,
    currency: "EUR",
    rating: 4.8,
    address: "Calwer Straße 25, 70173 Stuttgart",
    tags: ["bitcoin", "crypto", "meetup", "networking", "free", "blockchain"],
  },
  {
    id: "event-2",
    name: "Ethereum Developer Meetup",
    description: "Weekly coding sessions for Ethereum devs. Beginners welcome!",
    category: "event",
    coordinates: { lat: 48.7801, lng: 9.1856 },
    price: 0,
    currency: "EUR",
    rating: 4.5,
    address: "Hackathon Space, Königstraße 46",
    tags: ["ethereum", "crypto", "developer", "coding", "meetup", "blockchain"],
  },
  {
    id: "event-3",
    name: "Stuttgart Jazz Open",
    description: "Annual jazz festival in July. World-class musicians, outdoor stages.",
    category: "event",
    coordinates: { lat: 48.7785, lng: 9.1795 },
    price: 45,
    currency: "EUR",
    rating: 4.9,
    address: "Schlossplatz, 70173 Stuttgart",
    tags: ["jazz", "music", "festival", "concert", "outdoor"],
  },

  // ACTIVITIES - MUSIC
  {
    id: "music-1",
    name: "Musikschule Stuttgart",
    description: "Learn any instrument! Guitar, piano, drums. Trial lessons available.",
    category: "activity",
    coordinates: { lat: 48.7723, lng: 9.1678 },
    price: 30,
    currency: "EUR",
    rating: 4.6,
    address: "Rotebühlplatz 28, 70173 Stuttgart",
    tags: ["music", "learn", "guitar", "piano", "drums", "lessons", "school"],
  },
  {
    id: "music-2",
    name: "Rockshop Music Academy",
    description: "Rock and pop music school. Band workshops and solo lessons.",
    category: "activity",
    coordinates: { lat: 48.7698, lng: 9.1623 },
    price: 25,
    currency: "EUR",
    rating: 4.4,
    address: "Schwabstraße 45, 70197 Stuttgart",
    tags: ["music", "learn", "rock", "band", "guitar", "lessons"],
  },

  // NIGHTLIFE
  {
    id: "bar-1",
    name: "Sky Beach Stuttgart",
    description: "Rooftop bar with city views. Great cocktails, chill vibes.",
    category: "nightlife",
    coordinates: { lat: 48.7756, lng: 9.1712 },
    price: 10,
    currency: "EUR",
    rating: 4.3,
    address: "Königstraße 6, 70173 Stuttgart",
    tags: ["bar", "rooftop", "cocktails", "views", "chill"],
  },
  {
    id: "club-1",
    name: "Climax Institutes",
    description: "Underground techno club. Best sound system in the city.",
    category: "nightlife",
    coordinates: { lat: 48.7834, lng: 9.1923 },
    price: 15,
    currency: "EUR",
    rating: 4.7,
    address: "Forststraße 15, 70176 Stuttgart",
    tags: ["club", "techno", "electronic", "dance", "nightclub"],
  },

  // SERVICES
  {
    id: "service-1",
    name: "Coworking0711",
    description: "Modern coworking space. Day passes 15€, monthly from 150€.",
    category: "service",
    coordinates: { lat: 48.7789, lng: 9.1834 },
    price: 15,
    currency: "EUR",
    rating: 4.5,
    address: "Charlottenstraße 29, 70182 Stuttgart",
    tags: ["coworking", "office", "wifi", "workspace", "freelancer"],
  },
  {
    id: "service-2",
    name: "Stadtbibliothek Stuttgart",
    description: "Stunning modern library. Free entry, free WiFi, quiet study areas.",
    category: "service",
    coordinates: { lat: 48.7887, lng: 9.1856 },
    price: 0,
    currency: "EUR",
    rating: 4.9,
    address: "Mailänder Platz 1, 70173 Stuttgart",
    tags: ["library", "free", "wifi", "study", "books", "quiet"],
  },
];


